added image and description of API
pooltogether/v4-docs pull request #3
Opened 2021-12-01 00:05 UTC by aodhgan

2021-12-01 22:25 UTC, asselstine requested changes
I would say the page you create could be moved into Concepts, and a reference page is added
That ref page should cover:

- What the API provides (claimable prizes)
- How to access the API (show actual URL format)
- What the data looks like (prize structure)

2021-12-08 19:57 UTC, asselstine commented
Some things I noticed:

- The "Prizes API" section in Concepts isn't really a concept.  It's describing how the HTTP api is built.
- The references "Prizes API" section doesn't have a title "Prize API" with an introduction explaining what it does.  Don't rely on a link.

Changes I'd like to see:

- Change the "Prize API" concepts section to "Computing Prizes" and describe how to compute prizes **conceptually**.  I.e. the data needed and the formulas.  On that page you can then have sub-sections describing the tools (the CLI and the API which just wraps the CLI).
- The reference Prize API section is pretty good, but needs a proper title and in-line description of what it is.  Describe in one simple sentence what this does.
- The reference Prize API description should set the stage for the sub-sections below.  Each should have a tldr description.  [This page](http://localhost:3000/protocol/concepts/prize-pools-network) is a good example.  Description sets the stage for the more detailed content below.

2021-12-08 19:59 UTC, asselstine commented
Couple more:

- change the word `degree` in the other sections to `tier`, as we should be consistent in our language
- don't use the word `awardable` prize.  it doesn't mean anything.

2021-12-11 02:18 UTC, aodhgan commented on docs/reference/prize-api.md
> +# Prize Data Lifecycle Overview
This section doesnt really fit here anymore. Just take the hit and delete it? @asselstine

2021-12-13 19:21 UTC, aodhgan commented
Netlify builds dont seem to see static image files or something

![Screen Shot 2021-12-13 at 11 19 48 AM](https://user-images.githubusercontent.com/36907214/145874580-f50e7e4b-df6c-4d70-8078-b73be780a873.png)

2021-12-13 22:23 UTC, asselstine reviewed
Broadly:

The API reference is pretty good.  But- you're right in that the Prize Data Lifecycle section isn't a good fit there.  I think that section should be moved to the v4-draw-results project README, because it explains how that pipeline works.

The "Computing Prizes" page doesn't actually explain how prizes are computed.  It talks about how the Draw Calculator contract computes the prizes and says that it's possible off-chain.  No links are provided, no details are provided.

Computing prizes should detail what the high-level steps of the algorithm are:

- Get the Draw & Prize Distribution from the contract DrawBuffer and PrizeDistBuffer
- compute the user's TWAB for the draw given the draw start, beacon period & offsets
- compute the number of picks a user gets
- for each pick, compute the PRNG and compare it to winning number

Then below that you can allude to how you can calculate it yourself using the lib or cli, or access the prizes we've computed using those tools via the API.

2021-12-15 19:08 UTC, asselstine approved these changes

2021-12-15 19:08 UTC, asselstine commented on docs/concepts/computing-prizes.md
> +- Compute the user's TWAB for the draw given the draw start teimstamp, beacon period & offsets
*timestamp

2021-12-15 20:02 UTC, merged