Add Twab Rewards how to section
pooltogether/v4-docs pull request #6
Opened 2022-01-11 00:51 UTC by PierrickGT

2022-01-11 03:46 UTC, asselstine commented
You need to provide more context and introduce the concepts.

# Provide More Context

The first line is: "The Twab Rewards contract allow anyone to create a promotion for depositors into a pool."

Whats a promotion?  Use common terms so that someone who knows nothing about PoolTogether will understand.  i.e. "The Twab Rewards allow you to distribute tokens to prize pool depositors." 

"This contract being tied to a pool, it is important that you first verify that the Twab Rewards contract you are interacting with is tied to the pool you want to create the promotion for."

What is this sentence trying to say?

# Separate Into Sections

You need to explain the use case, explain how it works, then provide the tutorial.  The tutorial should have a high level description of what it does, then provide a separate section for each step.



At a high level you can break technical writing down like so:

1. Introduce your subject.  Describe at a high level what you are about to explain.  Give a brief introduction and context to each of the topics you cover.
2. Go into detail on each of the topics you will cover.
3. Summarize what you have explained

2022-01-11 03:46 UTC, asselstine requested changes
See comments

2022-01-12 17:58 UTC, PierrickGT commented
> "This contract being tied to a pool, it is important that you first verify that the Twab Rewards contract you are interacting with is tied to the pool you want to create the promotion for."
> What is this sentence trying to say?

It's to explain that we have one contract per pool/ticket.

2022-01-17 16:28 UTC, asselstine approved these changes

2022-01-18 17:55 UTC, merged